###Ejercicio 1. Limpieza e imputación de un conjunto de datos mixto

In [66]:
#importación de librerias

import numpy as np
import pandas as pd

In [67]:
#creación del dataframe

df = pd.DataFrame({
    'Nombre': ['Ana', 'Luis', 'Pedro', None, 'Marta', 'Luis', 'Sofía'],
    'Edad': [25, np.nan, 35, 29, -5, 25, None],
    'Ciudad': ['Bogotá', 'Medellín', None, 'Medellín', 'Cali', 'Bogotá', 'Cali'],
    'Ingreso': [3500, 4800, np.nan, 5200, 5100, np.nan, 4700],
    'FechaIngreso': ['2023-01-01', '2023-01-05', None, '2023-01-10', '2023-01-12', None, '2023-01-15']
})

In [68]:
df.info()

df

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7 entries, 0 to 6
Data columns (total 5 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Nombre        6 non-null      object
 1   Edad          5 non-null      float64
 2   Ciudad        6 non-null      object
 3   Ingreso       5 non-null      float64
 4   FechaIngreso  5 non-null      object
dtypes: float64(2), object(3)
memory usage: 412.0+ bytes

  Nombre  Edad    Ciudad  Ingreso FechaIngreso
0    Ana  25.0    Bogotá   3500.0   2023-01-01
1   Luis   NaN  Medellín   4800.0   2023-01-05
2  Pedro  35.0      None      NaN         None
3   None  29.0  Medellín   5200.0   2023-01-10
4  Marta  -5.0      Cali   5100.0   2023-01-12
5   Luis  25.0    Bogotá      NaN         None
6  Sofía   NaN      Cali   4700.0   2023-01-15

In [69]:
#Detección de valores faltantes
df.isnull().sum()

Nombre          1
Edad            2
Ciudad          1
Ingreso         2
FechaIngreso    2
dtype: int64

In [70]:
#Correción de valores faltantes columna "Nombre"
# Reemplazamos los valores faltantes (NaN) por la palabra "Desconocido"

df["Nombre"] = df["Nombre"].fillna("Desconocido")

#Correción de valores faltantes columna "Edad"
# Reemplazamos las edades negativas por NaN y luego llenamos los valores faltantes con la mediana.

df['Edad'] = df['Edad'].apply(lambda x: np.nan if x is None or x < 0 else x)
df['Edad'] = df['Edad'].fillna(df['Edad'].median())

#Correción de valores faltantes columna "Ciudad"
# Se reemplazan los valores faltantes con la moda (la ciudad que más se repite)

ciudad_mode = df['Ciudad'].mode(dropna=True)
if len(ciudad_mode) > 0:
    ciudad_mode = ciudad_mode[0]
else:
    ciudad_mode = 'Desconocida'
df['Ciudad'] = df['Ciudad'].fillna(ciudad_mode)

#Correción de valores faltantes columna "Ingreso" con la mediana
# Se usa la mediana porque es más robusta ante valores extremos que la media.

df['Ingreso'] = df['Ingreso'].fillna(df['Ingreso'].median())


#Correción de formato de fecha en columna "FechaIngreso"
# Convertimos las fechas a formato datetime y reemplazamos los valores nulos por la moda.

df['FechaIngreso'] = pd.to_datetime(df['FechaIngreso'], errors='coerce')
fecha_moda = df['FechaIngreso'].mode()[0]
df['FechaIngreso'] = df['FechaIngreso'].fillna(fecha_moda)

In [71]:
df

        Nombre  Edad    Ciudad  Ingreso FechaIngreso
0          Ana  25.0    Bogotá   3500.0   2023-01-01
1         Luis  27.0  Medellín   4800.0   2023-01-05
2        Pedro  35.0    Bogotá   4800.0   2023-01-01
3  Desconocido  29.0  Medellín   5200.0   2023-01-10
4        Marta  27.0      Cali   5100.0   2023-01-12
5         Luis  25.0    Bogotá   4800.0   2023-01-01
6        Sofía  27.0      Cali   4700.0   2023-01-15

###Ejercicio 2. Limpieza de duplicados

In [72]:
df = pd.DataFrame({
    'ID': [101, 102, 102, 103, 104, 104, 104],
    'Nombre': ['Ana', 'Luis', 'Luis', 'Marta', 'Carlos', 'Carlos', 'Carlos'],
    'Edad': [25, 30, 30, 29, 40, 40, 41],
    'Ciudad': ['Bogotá', 'Cali', 'Cali', 'Medellín', 'Cali', 'Cali', 'Cali'],
    'FechaRegistro': ['2023-01-01', '2023-01-05', '2023-01-05', '2023-01-10',
                    '2023-01-15', '2023-01-15', '2023-01-16']
})

In [73]:
df

    ID  Nombre  Edad    Ciudad FechaRegistro
0  101     Ana    25    Bogotá    2023-01-01
1  102    Luis    30      Cali    2023-01-05
2  102    Luis    30      Cali    2023-01-05
3  103   Marta    29  Medellín    2023-01-10
4  104  Carlos    40      Cali    2023-01-15
5  104  Carlos    40      Cali    2023-01-15
6  104  Carlos    41      Cali    2023-01-16

In [74]:
total_registros = len(df)
print(f"Total de registros originales: {total_registros}")

Total de registros originales: 7

In [75]:
duplicados_exactos = df[df.duplicated(keep=False)]
print("Duplicados exactos:")
print(duplicados_exactos)

cantidad_duplicados_exactos = df.duplicated().sum()
print(f"Cantidad de duplicados exactos: {cantidad_duplicados_exactos}")

Duplicados exactos:
    ID  Nombre  Edad Ciudad FechaRegistro
1  102    Luis    30   Cali    2023-01-05
2  102    Luis    30   Cali    2023-01-05
4  104  Carlos    40   Cali    2023-01-15
5  104  Carlos    40   Cali    2023-01-15
Cantidad de duplicados exactos: 2

In [76]:
duplicados_id_nombre = df[df.duplicated(subset=['ID', 'Nombre'], keep=False)]
print("Duplicados por ID y Nombre:")
print(duplicados_id_nombre)

cantidad_duplicados_id_nombre = df.duplicated(subset=['ID', 'Nombre']).sum()
print(f"Cantidad de duplicados por ID y Nombre: {cantidad_duplicados_id_nombre}")

Duplicados por ID y Nombre:
    ID  Nombre  Edad Ciudad FechaRegistro
1  102    Luis    30   Cali    2023-01-05
2  102    Luis    30   Cali    2023-01-05
4  104  Carlos    40   Cali    2023-01-15
5  104  Carlos    40   Cali    2023-01-15
6  104  Carlos    41   Cali    2023-01-16
Cantidad de duplicados por ID y Nombre: 3

In [77]:
# Eliminamos duplicados conservando el primer registro
df_limpio = df.drop_duplicates(subset=['ID', 'Nombre'], keep='first')

registros_eliminados = len(df) - len(df_limpio)
print(f"Registros eliminados: {registros_eliminados}")

Registros eliminados: 3

In [78]:
print(f"Registros después de la limpieza: {len(df_limpio)}")
print("\nDataFrame limpio:")
df_limpio

Registros después de la limpieza: 4

DataFrame limpio:

    ID  Nombre  Edad    Ciudad FechaRegistro
0  101     Ana    25    Bogotá    2023-01-01
1  102    Luis    30      Cali    2023-01-05
3  103   Marta    29  Medellín    2023-01-10
4  104  Carlos    40      Cali    2023-01-15

###Ejercicio 3. Corrección de errores tipográficos o de codificación

In [79]:

df = pd.DataFrame({
    'Ciudad': ['bogota', 'Bogotá', 'BOGOTA', 'bogotá', 'bogata', 'Bógota', 'BogoTa', 'Cali', 'calí', 'medellín', 'medellin']
})

In [80]:
df

      Ciudad
0     bogota
1     Bogotá
2     BOGOTA
3     bogotá
4     bogata
5     Bógota
6     BogoTa
7       Cali
8       calí
9   medellín
10  medellin

In [81]:
# Pasamos todo a minúsculas y eliminamos espacios en blanco
df['Ciudad'] = df['Ciudad'].str.lower().str.strip()

In [82]:
pip install Unidecode

Requirement already satisfied: Unidecode in /usr/local/lib/python3.12/dist-packages (1.4.0)

In [83]:
# Importamos función para eliminar acentos y aplicamos a cada valor

import unidecode
df['Ciudad'] = df['Ciudad'].apply(lambda x: unidecode.unidecode(x))

In [84]:
# Definimos un diccionario con las correcciones
correcciones = {
    'bogata': 'bogota',}

# Reemplazamos según el diccionario

df['Ciudad'] = df['Ciudad'].replace(correcciones)

In [85]:
print(df['Ciudad'].value_counts())

df

Ciudad
bogota      7
cali        2
medellin    2
Name: count, dtype: int64

      Ciudad
0     bogota
1     bogota
2     bogota
3     bogota
4     bogota
5     bogota
6     bogota
7       cali
8       cali
9   medellin
10  medellin